version: "3"
services:
  proxy:
    build: .
    volumes:
      - ./:/work
    environment:
      PORT: 8080
      APP_HOST: covid19.172.17.0.1.xip.st-sc.fr
    command: rerun --verbose --dir /work --signal TERM --background -- /work/dev/run
    ports:
      - 8080:8080
